apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 1 
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: drehnstrom/events-internal-del:v1.0
        env: 
        - name: GOOGLE_CLOUD_PROJECT
          value: "mar-roidtc600-instructor"
        ports:
        - containerPort: 8082

